[global]
; Run as daemon? Set to 'no' for Docker containers
daemonize = no

; PID file
pid = /var/run/php-fpm/php-fpm.pid

emergency_restart_threshold = 10
emergency_restart_interval = 1m
process_control_timeout = 10s

; Logging
; Error log in /var/log (www-data muss Schreibrechte haben)
error_log = /var/log/php-fpm/error.log
log_level = notice

; Include pool definitions
include=/usr/local/etc/php-fpm.d/*.conf