FROM registry.mceikens-infra.de/typo3-foss/php-fpm-84:2.3.0

USER root

RUN apk add --no-cache --virtual .build-deps \
    autoconf \
    g++ \
    make \
    linux-headers \
    git

# Xdebug manuell kompilieren (umgeht PECL komplett)
RUN git clone --depth 1 --branch 3.5.0 https://github.com/xdebug/xdebug.git /tmp/xdebug \
    && cd /tmp/xdebug \
    && phpize \
    && ./configure --enable-xdebug \
    && make -j$(nproc) \
    && make install \
    && rm -rf /tmp/xdebug

RUN curl -sS https://getcomposer.org/installer -o composer-setup.php \
    && php -d "disable_functions=" composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && rm composer-setup.php

RUN apk del .build-deps

# Xdebug aktivieren
RUN echo "zend_extension=xdebug.so" > /usr/local/etc/php/conf.d/99-xdebug.ini \
    && chown www-data:www-data /usr/local/etc/php/conf.d/99-xdebug.ini

USER www-data